#!/bin/bash
set -e
if $(/bin/ls /etc/udev/rules.d | /bin/grep -p '70-wii-tooth.rules'); then
	/bin/echo "udev rules already established. Continuing . . ."
else
	/bin/echo 'KERNEL=="uinput", GROUP="users"' >> /etc/udev/rules.d/70-wii-tooth.rules
	/bin/echo "udev rules established."
fi
if $(cat /etc/modules | grep -q "uinput"); then
	exit
else
	/bin/echo "uinput" >> /etc/modules
fi
