#!/bin/bash
echo 'KERNEL=="uinput", GROUP="users"' >> /etc/udev/rules.d/70-wii-tooth.rules
for a in /home/*; do
	echo -e "[Desktop Entry]\nName=Wii-Tooth Service\nComment=Wii Remote Driver configurator and key mapper\nGenericName=Wii-Tooth\nExec=wminput -d -c /etc/cwiid/wminput/wii-tooth-default.conf\nType=Application\nEncoding=UTF-8" >> "$a"/.config/autostart/wii-tooth.desktop
done
echo "uinput" >> /etc/modules
